### ISSUE TITLE
C Page Issue

### ISSUE THREAD

**Issue by GaneshT21** [ArthurSmid/little-help-book#10]
Tested C Pages. Tested the navigation and all the hyperlinks on each page. One hyperlink https://www.ccslc.org/housing-help on the "Catholic Community Services Springfield Center" page is not working.
https://little-help-book.netlify.app/table-of-contents-style-homepage/provider.html?place=recvmkMc0NYpTdKxM

![CatholicCommunityServicesSpringfieldCenter](https://user-images.githubusercontent.com/77949520/106412374-a2010a00-6415-11eb-8fd1-0a205166387d.PNG)

**Comment by ArthurSmid** [comment]
Updated url with: https://www.ccslc.org/rentassistance
