### ISSUE TITLE
Another C Page Issue

### ISSUE THREAD

**Issue by GaneshT21** [ArthurSmid/little-help-book#11]
Tested more C Pages. Tested the navigation and all the hyperlinks on each page. Only one hyperlink centrolatinoamericano.org on the "Centro Latino Americano" page is not working.
https://little-help-book.netlify.app/table-of-contents-style-homepage/provider.html?place=recVn5xcaojKEfvao

![CentroLatinoAmericano](https://user-images.githubusercontent.com/77949520/106412449-cf4db800-6415-11eb-8f02-4dcf828254a7.PNG)

**Comment by ArthurSmid** [comment]
The address is correct—it just couldn't load from Airtable without the https, and so I added this: https://centrolatinoamericano.org/
