### ISSUE TITLE
Laundry Unicorns - Eugene Memmonite Church

### ISSUE THREAD

**Issue by GaneshT21** [ArthurSmid/little-help-book#31]
There is a link present: https://www.facebook.com/176669245822976/posts/laundry-unicorns-is-going-tonight-working-through-the-new-voucher-system/1518298054993415/

I updated Airtable.

**Comment by ArthurSmid** [comment]
Rather than linking to a Facebook post, since that will quickly be out of date. The option that makes more sense could be: https://www.eugenemennonite.com/
